#!/usr/bin/env bash
set -euo pipefail

CN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CN_REGION_TOOL="${CN_ROOT}/tools/region_tool.py"
CN_PREPARE_DATA="${CN_ROOT}/tools/prepare_data.py"
REGIONS_JSON="${REGIONS_JSON:-${CN_ROOT}/data/regions.json}"
DATA_DIR="${DATA_DIR:-${CN_ROOT}/data}"
CN_RUNTIME_DIR="${CN_RUNTIME_DIR:-/var/lib/china-region-whitelist}"
CN_CONFIG_FILE="${CN_CONFIG_FILE:-/etc/china-region-whitelist.conf}"
CN_SERVICE_NAME="china-region-whitelist.service"
CN_CHAIN_NAME="CN_REGION_WHITELIST"
CN_SET_NAME="cn_region_whitelist"
CN_GITHUB_PROXY="${CN_GITHUB_PROXY:-https://gh-proxy.com/}"
CN_UPSTREAM_INDEX_URL="https://raw.githubusercontent.com/metowolf/iplist/master/docs/cncity.md"
CN_UPSTREAM_DATA_BASE_URL="https://raw.githubusercontent.com/metowolf/iplist/master/data/cncity"

cn_python() {
  if command -v python3 >/dev/null 2>&1; then
    python3 "$@"
  elif command -v python >/dev/null 2>&1; then
    python "$@"
  else
    echo "未找到 python3/python，无法读取本地地区数据。" >&2
    return 127
  fi
}

cn_region_tool() {
  cn_python "${CN_REGION_TOOL}" --regions-json "${REGIONS_JSON}" --data-dir "${DATA_DIR}" "$@"
}

cn_set_data_dir() {
  local output_dir="$1"
  REGIONS_JSON="${output_dir}/data/regions.json"
  DATA_DIR="${output_dir}/data"
}

cn_github_proxy_url() {
  local raw_url="$1"
  local proxy="${CN_GITHUB_PROXY}"
  case "${proxy}" in
    ""|direct|none)
      printf '%s\n' "${raw_url}"
      ;;
    */)
      printf '%s%s\n' "${proxy}" "${raw_url}"
      ;;
    *)
      printf '%s/%s\n' "${proxy}" "${raw_url}"
      ;;
  esac
}

cn_use_runtime_data_if_available() {
  if [[ -s "${CN_RUNTIME_DIR}/data/regions.json" && -d "${CN_RUNTIME_DIR}/data/regions" ]]; then
    cn_set_data_dir "${CN_RUNTIME_DIR}"
  fi
}

cn_update_runtime_data() {
  cn_require_root
  mkdir -p "${CN_RUNTIME_DIR}"

  local -a args
  args=(--output-dir "${CN_RUNTIME_DIR}" --refresh-index --force)
  if [[ -n "${CN_INDEX_URL:-}" ]]; then
    args+=(--index-url "${CN_INDEX_URL}")
  else
    args+=(--index-url "$(cn_github_proxy_url "${CN_UPSTREAM_INDEX_URL}")")
  fi
  if [[ -n "${CN_DATA_BASE_URL:-}" ]]; then
    args+=(--data-base-url "${CN_DATA_BASE_URL}")
  else
    args+=(--data-base-url "$(cn_github_proxy_url "${CN_UPSTREAM_DATA_BASE_URL}")")
  fi

  echo "正在同步最新地区 CIDR 数据（默认通过 GitHub 代理，可设置 CN_GITHUB_PROXY=direct 直连）..." >&2
  cn_python "${CN_PREPARE_DATA}" "${args[@]}"
  cn_set_data_dir "${CN_RUNTIME_DIR}"
}

cn_list_provinces() {
  cn_region_tool list-provinces
}

cn_list_cities() {
  cn_region_tool list-cities "$1"
}

cn_show_provinces() {
  cn_region_tool show-provinces
}

cn_show_cities() {
  cn_region_tool show-cities "$1"
}

cn_resolve_province() {
  cn_region_tool resolve-province "$1"
}

cn_resolve_city() {
  cn_region_tool resolve-city "$1" "$2"
}

cn_collect_cidrs() {
  cn_region_tool collect-cidrs "$@"
}

cn_render_apply_commands() {
  local client_ip="${1:-}"
  local forward_mode="${2:-all}"
  local forward_ifaces="${3:-}"
  shift 3 || true

  local -a args
  args=(render-apply)
  if [[ -n "${client_ip}" ]]; then
    args+=(--client-ip "${client_ip}")
  fi

  case "${forward_mode}" in
    all|"")
      ;;
    none)
      args+=(--no-forward)
      ;;
    selected)
      if [[ -z "${forward_ifaces}" ]]; then
        echo "已选择指定转发接口模式，但没有提供接口名。" >&2
        return 1
      fi
      local iface
      for iface in ${forward_ifaces}; do
        cn_validate_interface_name "${iface}" || return 1
        args+=(--forward-iface "${iface}")
      done
      ;;
    *)
      echo "未知转发接口模式：${forward_mode}" >&2
      return 1
      ;;
  esac

  cn_region_tool "${args[@]}" "$@"
}

cn_render_clear_commands() {
  cn_region_tool render-clear
}

cn_save_config() {
  cn_require_root
  local forward_mode="$1"
  local forward_ifaces="$2"
  shift 2 || true
  local -a codes=("$@")
  if [[ "${#codes[@]}" -eq 0 ]]; then
    echo "没有可保存的地区代码。" >&2
    return 1
  fi
  case "${forward_mode}" in
    all|none|selected) ;;
    *)
      echo "未知转发接口模式：${forward_mode}" >&2
      return 1
      ;;
  esac

  mkdir -p "$(dirname "${CN_CONFIG_FILE}")"
  {
    echo "# Generated by china-region-whitelist. Edit CN_CODES only if you know the region codes."
    printf 'CN_CODES="%s"\n' "${codes[*]}"
    printf 'CN_FORWARD_MODE="%s"\n' "${forward_mode}"
    printf 'CN_FORWARD_IFACES="%s"\n' "${forward_ifaces}"
    printf 'CN_ROOT="%s"\n' "${CN_ROOT}"
    printf 'CN_RUNTIME_DIR="%s"\n' "${CN_RUNTIME_DIR}"
  } > "${CN_CONFIG_FILE}"
  chmod 0644 "${CN_CONFIG_FILE}"
}

cn_source_config() {
  if [[ ! -r "${CN_CONFIG_FILE}" ]]; then
    echo "未找到配置文件：${CN_CONFIG_FILE}，请先运行 apply。" >&2
    return 1
  fi

  # shellcheck disable=SC1090
  source "${CN_CONFIG_FILE}"
}

cn_load_config_codes() {
  cn_source_config
  if [[ -z "${CN_CODES:-}" ]]; then
    echo "配置文件缺少 CN_CODES：${CN_CONFIG_FILE}" >&2
    return 1
  fi

  local code
  for code in ${CN_CODES}; do
    if ! [[ "${code}" =~ ^[0-9]{6}$ ]]; then
      echo "配置文件中存在非法地区代码：${code}" >&2
      return 1
    fi
    printf '%s\n' "${code}"
  done
}

cn_load_config_forward_mode() {
  cn_source_config
  printf '%s\n' "${CN_FORWARD_MODE:-all}"
}

cn_load_config_forward_ifaces() {
  cn_source_config
  local iface
  for iface in ${CN_FORWARD_IFACES:-}; do
    cn_validate_interface_name "${iface}" || return 1
    printf '%s\n' "${iface}"
  done
}

cn_install_systemd_service() {
  cn_require_root
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "未检测到 systemd，已应用当前规则，但无法自动配置开机恢复。" >&2
    return 0
  fi

  local service_path="/etc/systemd/system/${CN_SERVICE_NAME}"
  cat > "${service_path}" <<EOF
[Unit]
Description=china region whitelist firewall
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash ${CN_ROOT}/install.sh restore --update-optional

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable "${CN_SERVICE_NAME}"
}

cn_disable_systemd_service() {
  cn_require_root
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable "${CN_SERVICE_NAME}" >/dev/null 2>&1 || true
    rm -f "/etc/systemd/system/${CN_SERVICE_NAME}"
    systemctl daemon-reload || true
  fi
  rm -f "${CN_CONFIG_FILE}"
}

cn_show_persistence_status() {
  echo
  echo "== persistence =="
  if [[ -r "${CN_CONFIG_FILE}" ]]; then
    echo "config: ${CN_CONFIG_FILE}"
    # shellcheck disable=SC1090
    source "${CN_CONFIG_FILE}"
    echo "regions: ${CN_CODES:-未配置}"
    echo "forward: ${CN_FORWARD_MODE:-all}${CN_FORWARD_IFACES:+ (${CN_FORWARD_IFACES})}"
  else
    echo "config: 未配置"
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl is-enabled "${CN_SERVICE_NAME}" 2>/dev/null || true
  else
    echo "systemd: 未检测到"
  fi
}

cn_require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "此操作需要 root 权限，请使用 sudo 或 root 用户运行。" >&2
    exit 1
  fi
}

cn_install_dependencies() {
  echo "检测到缺少 iptables/ipset，开始使用系统默认软件源自动安装..." >&2

  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y iptables ipset
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y iptables ipset
  elif command -v yum >/dev/null 2>&1; then
    yum install -y iptables ipset
  elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache iptables ipset
  elif command -v zypper >/dev/null 2>&1; then
    zypper --non-interactive refresh || true
    zypper --non-interactive install iptables ipset
  else
    echo "未识别到 apt-get/dnf/yum/apk/zypper，无法自动安装 iptables/ipset。" >&2
    return 1
  fi
}

cn_require_commands() {
  local missing=0
  for command_name in iptables ipset; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
      echo "缺少命令：${command_name}" >&2
      missing=1
    fi
  done
  if [[ "${missing}" -ne 0 ]]; then
    cn_install_dependencies || {
      echo "自动安装失败，请检查系统软件源后重试。" >&2
      exit 1
    }
  fi

  missing=0
  for command_name in iptables ipset; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
      echo "安装后仍缺少命令：${command_name}" >&2
      missing=1
    fi
  done
  if [[ "${missing}" -ne 0 ]]; then
    echo "依赖未安装完整，请检查系统软件源或包名。" >&2
    exit 1
  fi
}

cn_detect_ssh_client_ip() {
  if [[ -n "${SSH_CONNECTION:-}" ]]; then
    awk '{print $1}' <<<"${SSH_CONNECTION}"
  else
    true
  fi
}

cn_validate_interface_name() {
  local iface="$1"
  if [[ "${iface}" =~ ^[A-Za-z0-9_.:-]{1,64}\+?$ ]]; then
    return 0
  fi
  echo "非法接口名：${iface}" >&2
  return 1
}

cn_list_network_interfaces() {
  if command -v ip >/dev/null 2>&1; then
    ip -o link show | awk -F': ' '{print $2}' | sed 's/@.*//' | sort -u
  elif [[ -d /sys/class/net ]]; then
    local iface_path
    for iface_path in /sys/class/net/*; do
      [[ -e "${iface_path}" ]] || continue
      basename "${iface_path}"
    done | sort -u
  fi
}

cn_is_tunnel_interface() {
  local iface="$1"
  if [[ -e "/sys/class/net/${iface}/tun_flags" ]]; then
    return 0
  fi
  case "${iface}" in
    tun*|tap*|wg*|tailscale*|ts*|zt*|utun*|warp*|nebula*|mihomo*|sing*|clash*)
      return 0
      ;;
  esac
  return 1
}

cn_list_tunnel_interfaces() {
  local iface
  while IFS= read -r iface; do
    [[ -n "${iface}" ]] || continue
    cn_is_tunnel_interface "${iface}" && printf '%s\n' "${iface}"
  done < <(cn_list_network_interfaces)
}

cn_run_rendered_commands() {
  local command_line
  while IFS= read -r command_line; do
    [[ -z "${command_line}" ]] && continue
    echo "+ ${command_line}"
    eval "${command_line}"
  done
}
