#!/usr/bin/env bash
set -euo pipefail

PO0_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PO0_REGION_TOOL="${PO0_ROOT}/tools/region_tool.py"
PO0_PREPARE_DATA="${PO0_ROOT}/tools/prepare_data.py"
REGIONS_JSON="${REGIONS_JSON:-${PO0_ROOT}/data/regions.json}"
DATA_DIR="${DATA_DIR:-${PO0_ROOT}/data}"
PO0_RUNTIME_DIR="${PO0_RUNTIME_DIR:-/var/lib/po0-region-whitelist}"
PO0_CONFIG_FILE="${PO0_CONFIG_FILE:-/etc/po0-region-whitelist.conf}"
PO0_SERVICE_NAME="po0-region-whitelist.service"
PO0_CHAIN_NAME="PO0_REGION_WHITELIST"
PO0_SET_NAME="po0_region_whitelist"

po0_python() {
  if command -v python3 >/dev/null 2>&1; then
    python3 "$@"
  elif command -v python >/dev/null 2>&1; then
    python "$@"
  else
    echo "未找到 python3/python，无法读取本地地区数据。" >&2
    return 127
  fi
}

po0_region_tool() {
  po0_python "${PO0_REGION_TOOL}" --regions-json "${REGIONS_JSON}" --data-dir "${DATA_DIR}" "$@"
}

po0_set_data_dir() {
  local output_dir="$1"
  REGIONS_JSON="${output_dir}/data/regions.json"
  DATA_DIR="${output_dir}/data"
}

po0_use_runtime_data_if_available() {
  if [[ -s "${PO0_RUNTIME_DIR}/data/regions.json" && -d "${PO0_RUNTIME_DIR}/data/regions" ]]; then
    po0_set_data_dir "${PO0_RUNTIME_DIR}"
  fi
}

po0_update_runtime_data() {
  po0_require_root
  mkdir -p "${PO0_RUNTIME_DIR}"

  local -a args
  args=(--output-dir "${PO0_RUNTIME_DIR}" --refresh-index --force)
  if [[ -n "${PO0_INDEX_URL:-}" ]]; then
    args+=(--index-url "${PO0_INDEX_URL}")
  fi
  if [[ -n "${PO0_DATA_BASE_URL:-}" ]]; then
    args+=(--data-base-url "${PO0_DATA_BASE_URL}")
  fi

  echo "正在同步最新地区 CIDR 数据..." >&2
  po0_python "${PO0_PREPARE_DATA}" "${args[@]}"
  po0_set_data_dir "${PO0_RUNTIME_DIR}"
}

po0_list_provinces() {
  po0_region_tool list-provinces
}

po0_list_cities() {
  po0_region_tool list-cities "$1"
}

po0_show_provinces() {
  po0_region_tool show-provinces
}

po0_show_cities() {
  po0_region_tool show-cities "$1"
}

po0_resolve_province() {
  po0_region_tool resolve-province "$1"
}

po0_resolve_city() {
  po0_region_tool resolve-city "$1" "$2"
}

po0_collect_cidrs() {
  po0_region_tool collect-cidrs "$@"
}

po0_render_apply_commands() {
  local client_ip="${1:-}"
  shift || true
  if [[ -n "${client_ip}" ]]; then
    po0_region_tool render-apply --client-ip "${client_ip}" "$@"
  else
    po0_region_tool render-apply "$@"
  fi
}

po0_render_clear_commands() {
  po0_region_tool render-clear
}

po0_save_config() {
  po0_require_root
  local -a codes=("$@")
  if [[ "${#codes[@]}" -eq 0 ]]; then
    echo "没有可保存的地区代码。" >&2
    return 1
  fi

  mkdir -p "$(dirname "${PO0_CONFIG_FILE}")"
  {
    echo "# Generated by po0 whitelist. Edit PO0_CODES only if you know the region codes."
    printf 'PO0_CODES="%s"\n' "${codes[*]}"
    printf 'PO0_ROOT="%s"\n' "${PO0_ROOT}"
    printf 'PO0_RUNTIME_DIR="%s"\n' "${PO0_RUNTIME_DIR}"
  } > "${PO0_CONFIG_FILE}"
  chmod 0644 "${PO0_CONFIG_FILE}"
}

po0_load_config_codes() {
  if [[ ! -r "${PO0_CONFIG_FILE}" ]]; then
    echo "未找到配置文件：${PO0_CONFIG_FILE}，请先运行 apply。" >&2
    return 1
  fi

  # shellcheck disable=SC1090
  source "${PO0_CONFIG_FILE}"
  if [[ -z "${PO0_CODES:-}" ]]; then
    echo "配置文件缺少 PO0_CODES：${PO0_CONFIG_FILE}" >&2
    return 1
  fi

  local code
  for code in ${PO0_CODES}; do
    if ! [[ "${code}" =~ ^[0-9]{6}$ ]]; then
      echo "配置文件中存在非法地区代码：${code}" >&2
      return 1
    fi
    printf '%s\n' "${code}"
  done
}

po0_install_systemd_service() {
  po0_require_root
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "未检测到 systemd，已应用当前规则，但无法自动配置开机恢复。" >&2
    return 0
  fi

  local service_path="/etc/systemd/system/${PO0_SERVICE_NAME}"
  cat > "${service_path}" <<EOF
[Unit]
Description=po0 region whitelist firewall
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash ${PO0_ROOT}/install.sh restore --update-optional

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable "${PO0_SERVICE_NAME}"
}

po0_disable_systemd_service() {
  po0_require_root
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable "${PO0_SERVICE_NAME}" >/dev/null 2>&1 || true
    rm -f "/etc/systemd/system/${PO0_SERVICE_NAME}"
    systemctl daemon-reload || true
  fi
  rm -f "${PO0_CONFIG_FILE}"
}

po0_show_persistence_status() {
  echo
  echo "== persistence =="
  if [[ -r "${PO0_CONFIG_FILE}" ]]; then
    echo "config: ${PO0_CONFIG_FILE}"
  else
    echo "config: 未配置"
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl is-enabled "${PO0_SERVICE_NAME}" 2>/dev/null || true
  else
    echo "systemd: 未检测到"
  fi
}

po0_require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "此操作需要 root 权限，请使用 sudo 或 root 用户运行。" >&2
    exit 1
  fi
}

po0_install_dependencies() {
  echo "检测到缺少 iptables/ipset，开始使用系统默认软件源自动安装..." >&2

  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y iptables ipset
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y iptables ipset
  elif command -v yum >/dev/null 2>&1; then
    yum install -y iptables ipset
  elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache iptables ipset
  elif command -v zypper >/dev/null 2>&1; then
    zypper --non-interactive refresh || true
    zypper --non-interactive install iptables ipset
  else
    echo "未识别到 apt-get/dnf/yum/apk/zypper，无法自动安装 iptables/ipset。" >&2
    return 1
  fi
}

po0_require_commands() {
  local missing=0
  for command_name in iptables ipset; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
      echo "缺少命令：${command_name}" >&2
      missing=1
    fi
  done
  if [[ "${missing}" -ne 0 ]]; then
    po0_install_dependencies || {
      echo "自动安装失败，请检查系统软件源后重试。" >&2
      exit 1
    }
  fi

  missing=0
  for command_name in iptables ipset; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
      echo "安装后仍缺少命令：${command_name}" >&2
      missing=1
    fi
  done
  if [[ "${missing}" -ne 0 ]]; then
    echo "依赖未安装完整，请检查系统软件源或包名。" >&2
    exit 1
  fi
}

po0_detect_ssh_client_ip() {
  if [[ -n "${SSH_CONNECTION:-}" ]]; then
    awk '{print $1}' <<<"${SSH_CONNECTION}"
  else
    true
  fi
}

po0_run_rendered_commands() {
  local command_line
  while IFS= read -r command_line; do
    [[ -z "${command_line}" ]] && continue
    echo "+ ${command_line}"
    eval "${command_line}"
  done
}
