#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASN_LIST="${CN_HOME_BROADBAND_ASNS_FILE:-${ROOT}/data/carriers/home-broadband-asns.tsv}"
OUTPUT="${CN_HOME_BROADBAND_FILE:-${ROOT}/data/carriers/home-broadband.txt}"
ASN_BASE_URL="${CN_ASN_BASE_URL:-https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as}"
WORK_DIR=""

cleanup() {
  [[ -n "${WORK_DIR:-}" ]] && rm -rf "${WORK_DIR}"
}
trap cleanup EXIT

if [[ ! -r "${ASN_LIST}" ]]; then
  echo "Missing home broadband ASN list: ${ASN_LIST}" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to refresh home broadband data." >&2
  exit 1
fi

WORK_DIR="$(mktemp -d)"
RAW_FILE="${WORK_DIR}/raw.txt"
SORTED_FILE="${WORK_DIR}/sorted.txt"
: > "${RAW_FILE}"

while IFS=$'\t' read -r raw_asn _carrier _description; do
  [[ "${raw_asn}" =~ ^AS[0-9]+$ ]] || continue
  asn="${raw_asn#AS}"
  url="${ASN_BASE_URL%/}/${asn}/ipv4-aggregated.txt"
  echo "[home-broadband] ${raw_asn} ${url}" >&2
  curl -fsSL --connect-timeout 20 --retry 2 --retry-delay 1 "${url}" \
    | awk 'NF && $0 !~ /^#/ && $0 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/[0-9]+$/ {print $0}' \
    >> "${RAW_FILE}"
done < "${ASN_LIST}"

LC_ALL=C sort -u "${RAW_FILE}" > "${SORTED_FILE}"
if [[ ! -s "${SORTED_FILE}" ]]; then
  echo "No home broadband IPv4 prefixes were downloaded." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT}")"
{
  echo "# Generated by tools/prepare_home_broadband_data.sh"
  echo "# ASN-level approximation; see home-broadband-asns.tsv for scope and limitations."
  cat "${SORTED_FILE}"
} > "${OUTPUT}.tmp"
mv "${OUTPUT}.tmp" "${OUTPUT}"
echo "Wrote ${OUTPUT} ($(wc -l < "${SORTED_FILE}" | tr -d ' ') prefixes)" >&2
